/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as HydrafacialRouteImport } from './routes/hydrafacial'
import { Route as HairRemovalRouteImport } from './routes/hair-removal'
import { Route as FullBodyLaserRouteImport } from './routes/full-body-laser'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const HydrafacialRoute = HydrafacialRouteImport.update({
  id: '/hydrafacial',
  path: '/hydrafacial',
  getParentRoute: () => rootRouteImport,
} as any)
const HairRemovalRoute = HairRemovalRouteImport.update({
  id: '/hair-removal',
  path: '/hair-removal',
  getParentRoute: () => rootRouteImport,
} as any)
const FullBodyLaserRoute = FullBodyLaserRouteImport.update({
  id: '/full-body-laser',
  path: '/full-body-laser',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/full-body-laser': typeof FullBodyLaserRoute
  '/hair-removal': typeof HairRemovalRoute
  '/hydrafacial': typeof HydrafacialRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/full-body-laser': typeof FullBodyLaserRoute
  '/hair-removal': typeof HairRemovalRoute
  '/hydrafacial': typeof HydrafacialRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/full-body-laser': typeof FullBodyLaserRoute
  '/hair-removal': typeof HairRemovalRoute
  '/hydrafacial': typeof HydrafacialRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/full-body-laser'
    | '/hair-removal'
    | '/hydrafacial'
    | '/sitemap.xml'
    | '/admin/leads'
    | '/admin/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/full-body-laser'
    | '/hair-removal'
    | '/hydrafacial'
    | '/sitemap.xml'
    | '/admin/leads'
    | '/admin/login'
  id:
    | '__root__'
    | '/'
    | '/full-body-laser'
    | '/hair-removal'
    | '/hydrafacial'
    | '/sitemap.xml'
    | '/admin/leads'
    | '/admin/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FullBodyLaserRoute: typeof FullBodyLaserRoute
  HairRemovalRoute: typeof HairRemovalRoute
  HydrafacialRoute: typeof HydrafacialRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hydrafacial': {
      id: '/hydrafacial'
      path: '/hydrafacial'
      fullPath: '/hydrafacial'
      preLoaderRoute: typeof HydrafacialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hair-removal': {
      id: '/hair-removal'
      path: '/hair-removal'
      fullPath: '/hair-removal'
      preLoaderRoute: typeof HairRemovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/full-body-laser': {
      id: '/full-body-laser'
      path: '/full-body-laser'
      fullPath: '/full-body-laser'
      preLoaderRoute: typeof FullBodyLaserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FullBodyLaserRoute: FullBodyLaserRoute,
  HairRemovalRoute: HairRemovalRoute,
  HydrafacialRoute: HydrafacialRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
